# Generated by Django 6.0.4 on 2026-05-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('avalible', 'Avalible'), ('unavalible', 'Unavalible')], max_length=50),
        ),
    ]
