# Generated by Django 6.0.4 on 2026-05-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('ISBN', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('publication_year', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
