# Generated by Django 6.0.4 on 2026-05-13 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admine',
        ),
    ]
